### ISSUE TITLE
Annotations sometimes not properly readable

### ISSUE THREAD

**Issue by steveteuber** [steveteuber/kubectl-graph#35]
Annotations are not properly readable because some of them contains too much information.
It would be great if we could remove `annotations` like that:

```yaml
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {...}
    k8s.v1.cni.cncf.io/network-status: |-
      [{...}]
```
